# Generated by Django 4.2.7 on 2023-11-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_revision',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('type1', 'type1'), ('type2', 'type2')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='vendor',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['type'], name='main_file_type_a0a91a_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['vendor'], name='main_file_vendor_ffb407_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['date_revision'], name='main_file_date_re_ed753f_idx'),
        ),
    ]
