# Generated by Django 4.2.7 on 2023-11-18 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filedb', '0003_alter_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['id'], name='main_file_id_bab147_idx'),
        ),
    ]
